source ENV['GEM_SOURCE'] || "https://rubygems.org"

group :test do
  gem 'rake', '~> 1.0',                                             :require => false if RUBY_VERSION < '2.2.2'
  gem 'puppet', ENV['PUPPET_GEM_VERSION'] || '~> 3.8.0'
  gem 'puppetlabs_spec_helper', '~> 2.2.0',                         :require => false
  gem "rspec", '< 3.2.0'
  gem 'rspec-puppet', '~> 2.5',                                     :require => false
  gem 'rspec-puppet-facts',                                         :require => false
  gem 'rspec-puppet-utils',                                         :require => false
  gem 'metadata-json-lint',                                         :require => false
  gem 'puppet-blacksmith',                                          :require => false
  gem 'puppet-strings', '~> 1.0',                                   :require => false
  gem 'rubocop', '~> 0.49.1',                                       :require => false if RUBY_VERSION >= '2.3.0'
  gem 'rubocop-rspec', '~> 1.15.0',                                 :require => false if RUBY_VERSION >= '2.3.0'
  gem 'simplecov', '>= 0.11.0'
  gem 'simplecov-console',                                          :require => false

  gem 'github_changelog_generator', '~> 1.13.0',                    :require => false if RUBY_VERSION < '2.2.2'
  gem 'github_changelog_generator',                                 :require => false if RUBY_VERSION >= '2.2.2'
  gem 'parallel_tests',                                             :require => false

  gem 'puppet-lint-leading_zero-check',                             :require => false
  gem 'puppet-lint-trailing_comma-check',                           :require => false
  gem 'puppet-lint-version_comparison-check',                       :require => false
  gem 'puppet-lint-classes_and_types_beginning_with_digits-check',  :require => false
  gem 'puppet-lint-unquoted_string-check',                          :require => false
  gem 'puppetlabs_spec_helper', '~> 2.2.0',                         :require => false
  gem 'puppet-lint-variable_contains_upcase',                       :require => false

  gem 'json_pure', '<= 2.0.1' if RUBY_VERSION < '2.0.0'
end

group :development do
  gem 'travis'              if RUBY_VERSION >= '2.1.0'
  gem 'travis-lint'         if RUBY_VERSION >= '2.1.0'
  gem 'guard-rake'          if RUBY_VERSION >= '2.2.5' # per dependency https://rubygems.org/gems/ruby_dep
end

group :system_tests do
  gem 'beaker'
  gem 'beaker-rspec'
  gem 'serverspec',                    :require => false
  gem 'beaker-puppet_install_helper',  :require => false
end
